name: Ejecutar Tests de Python

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Ejecutar los tests
      run: python -m unittest discover -v GestionPaquetes

